--
-- PostgreSQL database dump
--

\restrict l23wxJkGItLpdvYco3n9lCGPwMejWxCQCuGdpXd0mP0XA3hiDFNtUcOyhXjawcs

-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: registry_emergencycontact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registry_emergencycontact (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    relationship character varying(50) NOT NULL,
    household_id bigint NOT NULL
);


ALTER TABLE public.registry_emergencycontact OWNER TO postgres;

--
-- Name: registry_emergencycontact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registry_emergencycontact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registry_emergencycontact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registry_household; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registry_household (
    id bigint NOT NULL,
    address text NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    evacuation_priority integer NOT NULL,
    zone_id bigint NOT NULL
);


ALTER TABLE public.registry_household OWNER TO postgres;

--
-- Name: registry_household_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registry_household ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registry_household_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registry_mobilityprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registry_mobilityprofile (
    id bigint NOT NULL,
    has_reduced_mobility boolean NOT NULL,
    mobility_type character varying(100) NOT NULL,
    needs_assistance boolean NOT NULL,
    notes text NOT NULL,
    resident_id bigint NOT NULL
);


ALTER TABLE public.registry_mobilityprofile OWNER TO postgres;

--
-- Name: registry_mobilityprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registry_mobilityprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registry_mobilityprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registry_monthlyavailability; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registry_monthlyavailability (
    id bigint NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    status character varying(20) NOT NULL,
    return_date date,
    household_id bigint NOT NULL,
    CONSTRAINT registry_monthlyavailability_month_check CHECK ((month >= 0)),
    CONSTRAINT registry_monthlyavailability_year_check CHECK ((year >= 0))
);


ALTER TABLE public.registry_monthlyavailability OWNER TO postgres;

--
-- Name: registry_monthlyavailability_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registry_monthlyavailability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registry_monthlyavailability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registry_resident; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registry_resident (
    id bigint NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    birth_date date NOT NULL,
    phone character varying(20) NOT NULL,
    is_primary boolean NOT NULL,
    household_id bigint NOT NULL
);


ALTER TABLE public.registry_resident OWNER TO postgres;

--
-- Name: registry_resident_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registry_resident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registry_resident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registry_zone; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registry_zone (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    municipality character varying(100) NOT NULL,
    risk_level integer NOT NULL
);


ALTER TABLE public.registry_zone OWNER TO postgres;

--
-- Name: registry_zone_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.registry_zone ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registry_zone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registry_emergencycontact registry_emergencycontact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_emergencycontact
    ADD CONSTRAINT registry_emergencycontact_pkey PRIMARY KEY (id);


--
-- Name: registry_household registry_household_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_household
    ADD CONSTRAINT registry_household_pkey PRIMARY KEY (id);


--
-- Name: registry_mobilityprofile registry_mobilityprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_mobilityprofile
    ADD CONSTRAINT registry_mobilityprofile_pkey PRIMARY KEY (id);


--
-- Name: registry_mobilityprofile registry_mobilityprofile_resident_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_mobilityprofile
    ADD CONSTRAINT registry_mobilityprofile_resident_id_key UNIQUE (resident_id);


--
-- Name: registry_monthlyavailability registry_monthlyavailability_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_monthlyavailability
    ADD CONSTRAINT registry_monthlyavailability_pkey PRIMARY KEY (id);


--
-- Name: registry_resident registry_resident_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_resident
    ADD CONSTRAINT registry_resident_pkey PRIMARY KEY (id);


--
-- Name: registry_zone registry_zone_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_zone
    ADD CONSTRAINT registry_zone_pkey PRIMARY KEY (id);


--
-- Name: registry_emergencycontact_household_id_41314e8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registry_emergencycontact_household_id_41314e8b ON public.registry_emergencycontact USING btree (household_id);


--
-- Name: registry_household_zone_id_4bd04f8d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registry_household_zone_id_4bd04f8d ON public.registry_household USING btree (zone_id);


--
-- Name: registry_monthlyavailability_household_id_6f999cbf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registry_monthlyavailability_household_id_6f999cbf ON public.registry_monthlyavailability USING btree (household_id);


--
-- Name: registry_resident_household_id_45f6612b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX registry_resident_household_id_45f6612b ON public.registry_resident USING btree (household_id);


--
-- Name: registry_emergencycontact registry_emergencyco_household_id_41314e8b_fk_registry_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_emergencycontact
    ADD CONSTRAINT registry_emergencyco_household_id_41314e8b_fk_registry_ FOREIGN KEY (household_id) REFERENCES public.registry_household(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: registry_household registry_household_zone_id_4bd04f8d_fk_registry_zone_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_household
    ADD CONSTRAINT registry_household_zone_id_4bd04f8d_fk_registry_zone_id FOREIGN KEY (zone_id) REFERENCES public.registry_zone(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: registry_mobilityprofile registry_mobilitypro_resident_id_c991a24c_fk_registry_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_mobilityprofile
    ADD CONSTRAINT registry_mobilitypro_resident_id_c991a24c_fk_registry_ FOREIGN KEY (resident_id) REFERENCES public.registry_resident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: registry_monthlyavailability registry_monthlyavai_household_id_6f999cbf_fk_registry_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_monthlyavailability
    ADD CONSTRAINT registry_monthlyavai_household_id_6f999cbf_fk_registry_ FOREIGN KEY (household_id) REFERENCES public.registry_household(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: registry_resident registry_resident_household_id_45f6612b_fk_registry_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registry_resident
    ADD CONSTRAINT registry_resident_household_id_45f6612b_fk_registry_ FOREIGN KEY (household_id) REFERENCES public.registry_household(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict l23wxJkGItLpdvYco3n9lCGPwMejWxCQCuGdpXd0mP0XA3hiDFNtUcOyhXjawcs

